module.exports = {
  "ALIVE_IMG": "https://telegra.ph/file/6556dc26b017d8fa254de.jpg.jpeg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "public",
  "BOT_NUMBER": "923034830074",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": true,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": false,
  "ANTI_BAD": true,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "⸙🇲ᎯᎻᎬᏒ֎ᏰᎯᏰᎯ ᳀",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "ANTI_CALL": true
};
