module.exports = {
  "SESSION_ID": "ANJU-MD=GZkhwTCY#cHEoMPmtAGmOTfAaXhh3dnIk7Br6DhWyKIuqXJ7im7s",
  "ALIVE_IMG": "https://raw.githubusercontent.com/Mrrashmika/Database/refs/heads/main/WhatsApp%20Image%202024-09-08%20at%209.00.17%20PM.jpeg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "public",
  "BOT_NUMBER": "94717775628",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": true,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": false,
  "ANTI_BAD": true,
  "ANTI_BOT": true,
  "ANTI_LINK": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true
};
